version: "3"
services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  backend:
    depends_on:
      - mongodb
    build:
      dockerfile: Dockerfile
      context: ./TicketWave-Backend 
    volumes:
      - ./TicketWave-Backend/requirement.txt:/app/backend/requirement.txt
      - ./TicketWave-Backend/Ticketwave:/app/backend
    ports:
      - "8000:8000"

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./TicketWave-Frontend
    volumes:
      - /app/frontend/node_modules
      - ./TicketWave-Frontend/signup-login:/app/frontend
    ports:
      - "3000:3000"
