version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - SECRET_KEY = 'django-insecure-n=a2yox(rubsowm)xnqv^9!q-jut2krq*s9p)j%2hdg(4^7kcf'
      - MONGOHOST = 'mongodb+srv://jemmy:SFmskb4tFnNfoueg@cluster0.dol1pt8.mongodb.net/?retryWrites=true&w=majority'
  
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  backend:
    depends_on:
      - mongodb
    build:
      dockerfile: Dockerfile
      context: ./TicketWave-Backend 
    volumes:
      - ./TicketWave-Backend/Ticketwave:/app/backend
    environment:
      - SECRET_KEY = 'django-insecure-n=a2yox(rubsowm)xnqv^9!q-jut2krq*s9p)j%2hdg(4^7kcf'
      - MONGOHOST = 'mongodb+srv://jemmy:SFmskb4tFnNfoueg@cluster0.dol1pt8.mongodb.net/?retryWrites=true&w=majority'
    ports:
      - "8000:8000"

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./TicketWave-Frontend
    volumes:
      - /app/frontend/node_modules
      - ./TicketWave-Frontend/signup-login:/app/frontend
    ports:
      - "3000:3000"